### ISSUE TITLE
Im getting blank page But no error 

### ISSUE THREAD

**Issue by kamaldlk** [khankuan/react-sheet#4]
@khankuan  here my code converted fixed-data-table2 and react 16 
im using your methods and files 
please give me solution please look at my changes

https://github.com/kamaldlk/flexi-grid
![screen shot 2017-12-02 at 1 09 14 am](https://user-images.githubusercontent.com/9652523/33500053-71209994-d6fd-11e7-9116-7eb1163b94d1.png)

**Comment by yangshun** [comment]
@khankuan Not enough steps to reproduce. I propose closing this issue.

**Comment by kamaldlk** [comment]
@yangshun please clone https://github.com/kamaldlk/flexi-grid  and run your local It's working but im getting blank page cell render not working

**Comment by yangshun** [comment]
For starters, you should set the `width` and `height` of `.App`. I don't think the new version of Radium is working with the existing code as well as the inline styles are not being applied in your version.

**Comment by kamaldlk** [comment]
If i use Radium  with ur version it will work ? I gave request in FB please accept
